### ISSUE TITLE
Very Slow. =(

### ISSUE THREAD

**Issue by ScrapXD** [wrndxyz/Equinox#2]
So I noticed that the new update added many cool features, which caused it to be kinda slow. So what if you added a button in settings called "performance enhancement" and  when you turned it on, it became a little bit low quality, but faster

**Comment by wrownd** [comment]
Hello! Thanks for the feedback. That sounds like a good feature to add!

I’ll add a feature very similar to that and it’ll be out on Friday or Saturday. If I get a chance, I’ll push it as a patch early.

I’m in the works on looking at other VPS’s to handle the new load of users.

Thanks!!

**Comment by Rellyjell** [comment]
Sorry, but for me the YouTube app won't let me do anything it just has the search bar and when I type something in, it's just blank. I also tried this on the Google app, it does the same thing. Please help me!
